
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - oss.b2w.io
  resources:
  - queries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oss.b2w.io
  resources:
  - queries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oss.b2w.io
  resources:
  - restqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oss.b2w.io
  resources:
  - restqls/status
  verbs:
  - get
  - patch
  - update
